server:
  port: 80

spring:
  application:
    name: cloud-consumer-order

# 2.eureka配置 服务注册到哪里
eureka:
  client:
    #是否注册进eureka
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://127.0.0.1:7002/eureka/  #集群版



