server:
  port: 9527


spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由

      routes:
          - id: payment_routh  #payment_route       #路由的ID，没有固定规则但要求唯一，建议配合服务名
            uri: lb://CLOUD-PAYMENT-SERVICE      #匹配后提供服务的路由地址
            #uri: http://localhost:8001              #匹配后提供服务的路由地址
            predicates:
              - Path=/payment/get/**           #断言，路径相匹配的进行路由

          - id: payment_routh2  #payment_route       #路由的ID，没有固定规则但要求唯一，建议配合服务名
            uri: lb://CLOUD-PAYMENT-SERVICE      #匹配后提供服务的路由地址
            #uri: http://localhost:8001              #匹配后提供服务的路由地址
            predicates:
              - Path=/payment/lb/**            #断言，路径相匹配的进行路由
#              - Host=**.atguigu.com      #curl http://localhost:9527/payment/lb -H "Host:www.atguigu.com"
#              - Method=GET
#              - Query=username, \d+      #要有参数名username并且值还要是整数才能路由  curl http://localhost:9527/payment/lb?username=2
#              - Header=X-Request-Id, \d+       #请求头要有X-Request-Id属性并且值为整数的正则表达式 curl http://localhost:9527/payment/lb -H "X-Request-Id:123"
#              - After=2021-01-12T16:15:15.138+08:00[Asia/Shanghai]    #断言，路径相匹配的进行路由,时间是通过ZonedDateTime.now();获取的
#              - Cookie=username,wangguangyuan  #cmd --> curl http://localhost:9527/payment/lb --cookie "username=wangguangyuan"
#              - Before=2021-01-12T16:16:15.138+08:00[Asia/Shanghai]    #断言，路径相匹配的进行路由
#              - Between=2021-01-12T16:15:15.138+08:00[Asia/Shanghai],2021-01-12T16:16:15.138+08:00[Asia/Shanghai]

          - id: payment_routh3  #payment_route       #路由的ID，没有固定规则但要求唯一，建议配合服务名
            uri: http://localhost:8001              #匹配后提供服务的路由地址
#            filters:
#              - AddRequestParameter=username,wgy  #过滤器工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id值为1024
            predicates:
              - Path=/payment/feign/**           #断言，路径相匹配的进行路由

          - id: payment_routh4  #payment_route       #路由的ID，没有固定规则但要求唯一，建议配合服务名
            uri: http://news.baidu.com             #匹配后提供服务的路由地址
            predicates:
              - Path=/guonei           #断言，路径相匹配的进行路由

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: cloud-gateway
    prefer-ip-address: true