server:
  port: 80

spring:
  application:
    name: order-feign-consumer

# 2.eureka配置 服务注册到哪里
eureka:
  client:
    #是否注册进eureka
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://127.0.0.1:7002/eureka/  #集群版
  instance:
    instance-id: consumer-order-feign80
    prefer-ip-address: true


# openFeign的超时控制
#设置feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeOut: 5000



logging:
  level:
    com.atguigu.springcloud.service.PaymentFeignService: debug