server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: payment-hystrix-provider8001


