server:
  port: 80


spring:
  application:
    name: cloud-feign-hystrix-order

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/

  instance:
    instance-id: feign-hystrix-order80
    prefer-ip-address: true



# openFeign的超时控制
#设置feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeOut: 5000


feign:
  hystrix:
    enabled: true

